# Generated by Django 5.1.7 on 2025-03-29 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True)),
                ('allow_tributes', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorials', to=settings.AUTH_USER_MODEL)),
                ('profile_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='memorials.profilecode')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='memorials/photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='memorials.memorial')),
            ],
            options={
                'ordering': ['order', '-date_taken'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='memorials/timeline/%Y/%m/')),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='memorials.memorial')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='memorials.memorial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='memorials/videos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('date_recorded', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='memorials.memorial')),
            ],
            options={
                'ordering': ['order', '-date_recorded'],
            },
        ),
    ]
