# Generated by Django 5.1.7 on 2025-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorial',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Background image for the memorial page header', null=True, upload_to='memorials/background_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='memorial',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo of the person being commemorated', null=True, upload_to='memorials/profile_images/%Y/%m/'),
        ),
    ]
